name: ðŸ“¦ Build
run-name: ðŸ“¦ Build triggered
on: push
jobs:
  build:
    name: cesarolvr.com build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@master

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: install app dependencies
        run: yarn

      - name: building app
        run: yarn build

      - name: uploading to S3
        run: |
          aws s3 sync ./public s3://cesarolvr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id EI0DQ7VKOZ8XL --paths "/*" --region us-east-1
